### ISSUE TITLE
[Question] IcmpNode

### ISSUE THREAD

**Issue by RazvanN7** [sfu-arch/muir-lib#1]
I am trying to use muir which depends on muir-lib. When I'm trying to compile the generated scala sources from C code I noticed that the `==` node is lowered to an IcmpNode, however, IcmpNode does not exist in muir. Was there some refactorization? If yes, shouldn't muir be updated to generate the latest code for muir-lib?

**Comment by amsharifian** [comment]
Hi Razvan,
There was a minor refactoring of the code which we have done recently, but it seems the master branch doesn't have all the changes. Let me double-check and update the master if it's necessary.

**Comment by RazvanN7** [comment]
Thank you for the reply. I am waiting for the patches
